# Generated by Django 3.2.13 on 2022-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('parts', models.CharField(choices=[('klatka', 'klatka'), ('nogi', 'nogi'), ('barki', 'barki')], max_length=10)),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
